services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: eze
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes_db
      POSTGRES_TYPE: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: eze
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"